CREATE TABLE IF NOT EXISTS Regione (
    CodR INT PRIMARY KEY,
    Nome VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Provincia (
    siglaP CHAR(2) PRIMARY KEY,
    nome VARCHAR(20) NOT NULL,
    codR INT NOT NULL,
    FOREIGN KEY (codR) REFERENCES Regione(CodR)
        ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Comune (
    siglaP CHAR(2) NOT NULL,
    CAP INT PRIMARY KEY,
    nome VARCHAR(20) NOT NULL,
    FOREIGN KEY (siglaP) REFERENCES Provincia(siglaP)
        ON DELETE NO ACTION ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ASL (
    CodAsl INT,
    CAP INT,
    NomeASL VARCHAR(255) NOT NULL,
    Indirizzo VARCHAR(255) NOT NULL,
    PRIMARY KEY (CodAsl, CAP),
    FOREIGN KEY (CAP) REFERENCES Comune(CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Popolazione (
    CodAsl INT,
    CAP INT,
    AnnoR INT,
    RTotali INT,
    RAdulti INT,
    RInfanzia INT,
    RAnziani INT,
    PRIMARY KEY (CodAsl, CAP, AnnoR),
    FOREIGN KEY (CodAsl, CAP) REFERENCES ASL(CodAsl, CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Prescrizioni (
    CodAsl INT,
    CAP INT,
    AnnoR INT,
    NumeroRicette INT,
    ImportoR DECIMAL(10, 2),
    PRIMARY KEY (CodAsl, CAP, AnnoR),
    FOREIGN KEY (CodAsl, CAP) REFERENCES ASL(CodAsl, CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Personale(
    CodAsl INT,
    CAP INT,
    AnnoR INT NOT NULL,
    TipoMedico INT NOT NULL,
    Numero INT,
    PRIMARY KEY (CodAsl, CAP, AnnoR),
    FOREIGN KEY (CodAsl, CAP) REFERENCES ASL(CodAsl, CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (TipoMedico) REFERENCES TipoMedico(Id) 
        ON DELETE NO ACTION ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Strutture(
    CodAsl INT,
    CAP INT,
    AnnoR INT NOT NULL,
    TipoStruttura INT NOT NULL,
    Quantità INT,
    PRIMARY KEY (CodAsl, CAP, AnnoR),
    FOREIGN KEY (CodAsl, CAP) REFERENCES ASL(CodAsl, CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (TipoStruttura) REFERENCES TipoStruttura(Id) 
        ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS Servizi(
    CodAsl INT,
    CAP INT,
    AnnoR INT NOT NULL,
    TipoServizio INT NOT NULL, 
    Quantità INT,
    PRIMARY KEY (CodAsl, CAP, AnnoR),
    FOREIGN KEY (CodAsl, CAP) REFERENCES ASL(CodAsl, CAP)
        ON DELETE NO ACTION ON UPDATE CASCADE, 
    FOREIGN KEY (TipoServizio) REFERENCES TipoServizio(Id) 
        ON DELETE NO ACTION ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS TipoStruttura(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS TipoMedico(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS TipoServizio(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
